export const getStyles = () => {
  return {
    container: {
      flex: 1,
      backgroundColor: "black",
      paddingTop: 30,
      // paddingLeft: 15,
      // paddingRight: 15,
      gap: 15,
      width: "100%",
      // marginBottom: 15,

      // alignItems: "center",
      //  justifyContent: "center",
    },
    input: {
      //   margin: 15,
      height: 40,
      borderColor: "#5dacbd",
      color: "#24527a",
      borderWidth: 1,
      borderRadius: 10,
      paddingLeft: 10,
      width: "100%",
    },
    inputNot100: {
      //   margin: 15,
      height: 40,
      borderColor: "#5dacbd",
      color: "#24527a",
      borderWidth: 1,
      borderRadius: 10,
      paddingLeft: 10,
      //   flex: 1,
      width: "70%",
    },
    topBox: {
      backgroundColor: "black",
      display: "flex",
      flexDirection: "column",
      justifyContent: "flex-start",
      height: "auto",
      width: "80%",
      alignItems: "center",
      alignSelf: "center",
      paddingLeft: 8,
      marginTop: 15,
    },
    submitButton: {
      backgroundColor: "#5dacbd",
      //   flex: 1,
      padding: 10,
      height: 40,
      alignItems: "center",
      borderRadius: 10,
      paddingRight: 10,
      paddingLeft: 10,
    },
    submitButtonText: {
      color: "#e0ebeb",
      fontWeight: "bold",
    },
    resetText: {
      color: "blue",
      fontWeight: "bold",
    },
    leaveGameText: {
      color: "red",
      fontWeight: "bold",
    },
    submitButtonTextJa: {
      color: "green",
      fontWeight: "bold",
    },
    submitButtonTextNein: {
      color: "red",
      fontWeight: "bold",
    },
    middleButton: {
      alignSelf: "flex-start",
      display: "flex",
      flexDirection: "row",
      width: "80%",
      // gap: 10,
      //  justifyContent: "space-between",
    },
    headerLeftText: {
      fontSize: 20,
      color: "#24527a",
      marginTop: 15,
      alignSelf: "flex-start",
    },
    headerLeftTextPadding: {
      fontSize: 20,
      color: "#24527a",
      marginTop: 15,
      marginLeft: 15,
      alignSelf: "flex-start",
    },
    subheaderLeftText: {
      fontSize: 15,
      color: "#24527a",
      marginTop: 15,
      alignSelf: "flex-start",
    },
    headerCenterText: {
      fontSize: 20,
      color: "#24527a",
      marginTop: 15,
    },
    dropDown: {
      width: "100%",
      marginBottom: 15,
      marginTop: 10,
      zIndex: 3000,
    },
    dropDownNoIndex: {
      width: "100%",
      marginBottom: 15,
      marginTop: 10,
      zIndex: 0,
    },
    submitButton: {
      backgroundColor: "#5dacbd",
      padding: 10,
      marginBottom: 15,
      marginLeft: 15,
      marginRight: 15,
      height: 40,
      alignItems: "center",
      borderRadius: 10,
    },
    voteJa: {
      borderColor: "green",
      borderWidth: 3,
      padding: 10,
      marginBottom: 15,
      marginLeft: 15,
      marginRight: 15,
      height: 45,
      alignItems: "center",
      borderRadius: 10,
    },
    voteJaSelected: {
      backgroundColor: "green",
      borderColor: "green",
      padding: 10,
      marginBottom: 15,
      marginLeft: 15,
      marginRight: 15,
      height: 45,
      alignItems: "center",
      borderRadius: 10,
    },
    voteNein: {
      borderColor: "red",
      borderWidth: 3,
      padding: 10,
      marginBottom: 15,
      marginLeft: 15,
      marginRight: 15,
      height: 45,
      alignItems: "center",
      borderRadius: 10,
    },
    voteNeinSelected: {
      backgroundColor: "red",
      borderColor: "red",
      padding: 10,
      marginBottom: 15,
      marginLeft: 15,
      marginRight: 15,
      height: 45,
      alignItems: "center",
      borderRadius: 10,
    },
    resetAllVotes: {
      borderColor: "blue",
      borderWidth: 3,
      padding: 10,
      marginBottom: 15,
      marginLeft: 15,
      marginRight: 15,
      height: 45,
      alignItems: "center",
      borderRadius: 10,
    },
    leaveGame: {
      borderColor: "red",
      borderWidth: 3,
      padding: 10,
      marginBottom: 15,
      marginLeft: 15,
      marginRight: 15,
      height: 45,
      alignItems: "center",
      borderRadius: 10,
    },
    submitButtonJoin: {
      backgroundColor: "#5dacbd",
      padding: 10,
      marginBottom: 15,
      marginLeft: 15,
      marginRight: 15,
      height: 40,
      alignItems: "center",
      borderRadius: 10,
      //   width: "30%",
    },
    submitButtonRecommendations: {
      backgroundColor: "#24527a",
      padding: 10,
      marginBottom: 15,
      marginLeft: 15,
      marginRight: 15,
      marginTop: 20,
      height: 40,
      alignItems: "center",
      borderRadius: 10,
    },
    imageCenter: {
      objectFit: "contain",
      width: "90%",
    },
    imageBox: {
      flexDirection: "row",
      justifyContent: "center",
      height: "100%",
      display: "flex",
      width: "100%",
      alignItems: "center",
      alignSelf: "center",
      marginBottom: "auto",
      //  paddingLeft: 8,
      // marginTop: 15,
    },
  };
};
